# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: app-cert
# spec:
#   secretName: app-tls
#   issuerRef:
#     name: letsencrypt-staging
#     kind: ClusterIssuer
#   dnsNames:
#   - solarsystem.pramodh.in
