apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: solar-system-route
  namespace: development
spec:
  parentRefs:
  - name: nginx
    sectionName: https
    namespace: default
  hostnames:
  - solarsystem.pramodh.in
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: solar-system
      port: 3000