name: Solar system workflow

on:
    workflow_dispatch: 
    push: 
      branches:
        - main
        - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: Unit testing
        strategy:
          matrix:
            nodejs_version: [18,19,20]
            operating_system: [ubuntu-latest,windows-latest]
            exclude:
              - operating_system: windows-latest
          max-parallel: 1
          
        runs-on: ${{ matrix.operating_system }}
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: cache dependencies
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

        - name: Install dependencies
          run: npm install

        - name: Unit testing
          id: nodejs-unit-testing-step
          run: npm test

        - name: Archive test resultes
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: Macha-test-result-${{ matrix.operating_system }}-${{ matrix.nodejs_version}}
            path: test-results.xml

    code-coverage:
        name: Code-coverage
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Install dependencies
          run: npm install

        - name: Check code coverage
          continue-on-error: true
          run: npm run coverage

        - name: Archive test resultes
          uses: actions/upload-artifact@v4
          with:
            name: Code coverage result
            path: coverage
            retention-days: 5
    docker:
      name: docker build and push
      needs: [unit-testing,code-coverage]
      runs-on: ubuntu-latest
      steps:
        - name: checkout to repository
          uses: actions/checkout@v4

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Run Trivy vulnerability scan
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: kloude/node-test:v1.0.1
            format: 'json'
            severity: 'HIGH,CRITICAL'
            ignore-unfixed: true
            output: 'trivy-results.json'
            
          
        - name: Upload Vulnerability Scan Results
          uses: actions/upload-artifact@v4
          with:
            name: trivy-report
            path: trivy-report.json
            retention-days: 30
    
    

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: ${{ vars.DOCKER_USERNAME }}/node-test:v1.0.1