name: Solar system workflow

on:
    workflow_dispatch: 
    push: 
      branches:
        - main
        - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: Unit testing
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
        env:
          MONGO_URI: 'mongodb://localhost:27017/superData'
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password
        strategy:
          matrix:
            nodejs_version: [18,19,20]
            operating_system: [ubuntu-latest,windows-latest]
            exclude:
              - operating_system: windows-latest
          max-parallel: 1
          
        runs-on: ${{ matrix.operating_system }}
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: cache dependencies
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

        - name: Install dependencies
          run: npm install

        - name: Unit testing
          id: nodejs-unit-testing-step
          run: npm test

        - name: Archive test resultes
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: Macha-test-result-${{ matrix.operating_system }}-${{ matrix.nodejs_version}}
            path: test-results.xml

    code-coverage:
        name: Code-coverage
        container: 
          image: node:18
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            options: 
              --name mongo
        env:
          MONGO_URI: 'mongodb://mongo:27017/superData'
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Install dependencies
          run: npm install

        - name: Check code coverage
          continue-on-error: true
          run: npm run coverage

        - name: Archive test resultes
          uses: actions/upload-artifact@v4
          with:
            name: Code coverage result
            path: coverage
            retention-days: 5
    docker:
      name: docker build and push
      needs: [unit-testing,code-coverage]
      permissions:
        packages: write
      runs-on: ubuntu-latest
      steps:
        - name: checkout to repository
          uses: actions/checkout@v4

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Login to GHCR
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUBTOKEN }}
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: |
              kloude/node-test:${{ github.sha}}
              ghcr.io/${{github.repository_owner}}/node-test:${{ github.sha }}
    dev-deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Install kubectl CLI
          uses: azure/setup-kubectl@v4
          with:
            version: 'v1.34.0'
          id: install

        - uses: azure/k8s-set-context@v4
          with:
             method: kubeconfig
             kubeconfig: ${{ secrets.KUBECONFIG }} 


        - name: Fetch Kubernetes Cluster details
          run: |
            kubectl version
            echo --------------------------------
            kubectl get nodes
            kubectl get pods

        - name: Replace tokens in manifest file
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '{'
            tokenSuffix: '}'
            files: '["kubernetes/development/*.yaml"]'
          env:
            NAMESPACE: ${{ vars.NAMESPACE }}
            REPLICAS: ${{ vars.REPLICAS }}
            IMAGE: kloude/node-test:${{ github.sha}}

        - name: Show replaced files
          run: |
            ls -l kubernetes/development
            cat kubernetes/development/*.yaml

        - name: Create mongodb Secret
          run: |
            kubectl -n ${{ vars.NAMESPACE }} create secret generic  mongo-db-creds \
            --from-literal=MONGO_URI=${{ env.MONGO_URI }}
            --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }}
            --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
            --save-config
            --dry-run=client
            - o yaml | kubectl apply -f -

        - name: Deploy to Development namespace
          run: |
            kubectl apply -f kubernetes/development/deployment.yaml
            kubectl apply -f kubernetes/development/service.yaml